FROM alpine:3.3

ENV EDGE_REPOSITORY=http://dl-cdn.alpinelinux.org/alpine/edge/main
RUN apk update --repository $EDGE_REPOSITORY \
	&& apk add ffmpeg --repository $EDGE_REPOSITORY \
	&& apk add vlc --repository $EDGE_REPOSITORY \
        && apk add libav-tools --repository $EDGE_REPOSITORY \
	&& rm -rf /var/cache/apk/*
ENTRYPOINT ["avconv"]
